// <auto-generated />
using System;
using BillingPocTwo.BillingData.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BillingPocTwo.BillingData.Api.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    partial class BillingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BillingPocTwo.Shared.Entities.Billing.ENTITY_ADDRESS_INFO", b =>
                {
                    b.Property<decimal>("SEQ_ENTITY_ADDRESS_INFO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ADDRESS1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDRESS2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDRESS_TYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CITY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FULL_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SYSTEM_ENTITY_CODE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ZIP_CODE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SEQ_ENTITY_ADDRESS_INFO");

                    b.ToTable("ENTITY_ADDRESS_INFO", (string)null);
                });

            modelBuilder.Entity("BillingPocTwo.Shared.Entities.Billing.ENTITY_REGISTER", b =>
                {
                    b.Property<decimal>("SYSTEM_ENTITY_CODE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BALANCE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DOING_BUSINESS_AS_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ENTITY_TYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SOURCE_SYSTEM_ENTITY_CODE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SYSTEM_ENTITY_CODE");

                    b.ToTable("ENTITY_REGISTER", (string)null);
                });

            modelBuilder.Entity("BillingPocTwo.Shared.Entities.Billing.INT_BLNG_INQ_INV_DTL", b =>
                {
                    b.Property<decimal>("AUTO_KEY")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ACCOUNT_SYSTEM_CODE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ADJ_AMT_AFTER_LAST_INV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BALANCE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BILLING_INQ_REQ_SEQ")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CURRENT_MIN_DUE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ID_KEY")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LAST_INVOICE_AMT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LAST_INVOICE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LAST_INVOICE_DUE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NEXT_INST_DATE")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NEXT_INST_DUE_AMT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("NEXT_INS_DUE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PAST_DUE_AMT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PAY_RECVD_AFT_LAST_INV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PLEASE_PAY_AMT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("POLICY_TERM_ID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("REQ_SEQ_SERIAL_NO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("REQ_SEQ_SUB_SERIAL_NO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TOTAL_ADJUSTMENT_AMT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TOTAL_PAYMENT_AMT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TOTAL_RECV_AMT")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AUTO_KEY");

                    b.ToTable("INT_BLNG_INQ_INV_DTL", (string)null);
                });

            modelBuilder.Entity("BillingPocTwo.Shared.Entities.Billing.POLICY_ENTITY_REGISTER", b =>
                {
                    b.Property<decimal>("POLICY_TERM_ID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ENTITY_TYPE")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("SYSTEM_ENTITY_CODE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SYSTEM_ACTIVITY_NO")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("SYSTEM_TRANSACTION_SEQ")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BILLING_ENTITY_YN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ENTITY_TRANSACTION_SEQ")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LOCATION_ID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("POLICY_TERM_ID", "ENTITY_TYPE", "SYSTEM_ENTITY_CODE", "SYSTEM_ACTIVITY_NO", "SYSTEM_TRANSACTION_SEQ");

                    b.ToTable("POLICY_ENTITY_REGISTER", (string)null);
                });

            modelBuilder.Entity("BillingPocTwo.Shared.Entities.Billing.POLICY_REGISTER", b =>
                {
                    b.Property<decimal>("POLICY_TERM_ID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ACCOUNT_SYSTEM_CODE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("APPLICATION_NO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("BALANCE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BILL_TO_SYSTEM_CODE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BROKER_SYSTEM_CODE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("COUNTRY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CRT_CODE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EQUITY_DATE")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("INBOUND_TRANSACTION_SEQ")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("INSURED_SYSTEM_CODE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LEGAL_STATUS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OPERATING_COMPANY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PAYMENT_PLAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("POLICY_EFFECTIVE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("POLICY_EXPIRATION_DATE")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("POLICY_ID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("POLICY_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("POLICY_RENEW_NO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PRODUCT_CODE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ROWID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SOURCE_POLICY_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STATE_CODE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SUB_BILLTYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SYSTEM_STATUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SYSTEM_TRANSACTION_SEQ")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("POLICY_TERM_ID");

                    b.ToTable("POLICY_REGISTER", (string)null);
                });

            modelBuilder.Entity("BillingPocTwo.Shared.Entities.Billing.TRANSACTION_LOG", b =>
                {
                    b.Property<decimal>("SYSTEM_TRANSACTION_SEQ")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CREATED_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CREATED_ON")
                        .HasColumnType("datetime2");

                    b.Property<string>("POLICY_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("POLICY_TERM_ID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TRANSACTION_EFF_DATE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TRANSACTION_EXPIRY_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("TRANSACTION_TYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SYSTEM_TRANSACTION_SEQ");

                    b.ToTable("TRANSACTION_LOG", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
